[Info]

;Вариант. 0 - если у задачи нет вариантов. Числа 1, 2, ... если есть.
Variant=0

;Условие
Text="Функция А в блоке try вызывает функцию B, функция B вызывает С, а С генерирует исключение. Что произойдет?</p><p>"

;Сложность в диапазоне [1-5]
Difficulty=1

;Тема
Topic="Проталкивание исключений"

;ID Темы
TopicId=582

;Автор
Author="Желонкин А.В."

;Имя решателя (не изменять)
Solver="Test"

[Solution]
Type = "single"

Single = "Управление будет передано в соответствующий блок catch функции А"
ResponseOptions[]="Управление будет передано в соответствующий блок catch функции А"
ResponseOptions[]="Программа аварийно завершит работу из-за необрабатываемого исключения"
ResponseOptions[]="Управление будет передано на строку функции B, следующую за вызовом функции C"
ResponseOptions[]="Поведение не определено и полностью зависит от компилятора"



[DataBase]
TaskId=1100
GroupTaskId=1010
